<script setup>
import {LineChart} from "echarts/charts";import{GridComponent,TooltipComponent}from"echarts/components";import{graphic,init,use}from"echarts/core";import{CanvasRenderer}from"echarts/renderers";import{computed,nextTick,onBeforeUnmount,onMounted,reactive,ref,watch}from"vue";
import AiEntry from "./components/AiEntry.vue";import ConfirmDialog from "./components/ConfirmDialog.vue";import FoodPicker from "./components/FoodPicker.vue";import FoodLibraryView from "./components/FoodLibraryView.vue";import SettingsView from "./components/SettingsView.vue";import UnlockDialog from "./components/UnlockDialog.vue";
import {getDefaultMealType} from "./utils/mealType.js";
import {authFetch,ensureUnlocked,setUnlockHandler} from "./utils/auth.js";
import {cacheKeys,readCache,writeCache} from "./utils/cache.js";
import {notifyFoodUsageChanged} from "./utils/foodUsage.js";
use([LineChart,GridComponent,TooltipComponent,CanvasRenderer]);
const localDate=(d=new Date())=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);const localDateTime=(v=new Date())=>{const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
function moveSelectedDate(days){const date=new Date(`${selectedDate.value}T00:00:00`);date.setDate(date.getDate()+days);selectedDate.value=localDate(date)}function selectToday(){selectedDate.value=localDate()}
const readUrlState=()=>{const p=new URLSearchParams(location.search),view={"food-library":"foods",settings:"settings"}[p.get("view")]||"home",date=/^\d{4}-\d{2}-\d{2}$/.test(p.get("date")||"")?p.get("date"):localDate(),days=p.get("trend")==="30"?30:7;return{view,date,days}};const initialState=readUrlState();let applyingHistory=false;
const selectedDate=ref(initialState.date),records=ref([]),trend=ref([]),trendDays=ref(initialState.days),loading=ref(true),submitting=ref(false),errorMessage=ref(""),editingId=ref(null),inlineEditId=ref(null),inlineSaving=ref(false),recordToDelete=ref(null),deletingRecord=ref(false),unlockOpen=ref(false),unlocking=ref(false),unlockError=ref(""),currentView=ref(initialState.view),chartElement=ref(null),selectedFood=ref(null),inlineFood=ref(null);let chart,unlockResolve,unlockReject,dashboardRequestId=0,trendRequestId=0;const inlineDraft=reactive({quantity:"",unit:"g",meal_type:"",eaten_at:""});
const stats=reactive({total:0,breakfast:0,lunch:0,dinner:0,snack:0,protein:0,fat:0,carbs:0}),goals=reactive({calories:2000,protein:120,fat:65,carbs:250});
const blankRecord=()=>({food_name:"",quantity:"",unit:"g",food_id:null,protein:"",fat:"",carbs:"",alcohol_abv:0,nutrition_source:"manual",add_to_library:true,meal_type:getDefaultMealType(new Date()),eaten_at:`${selectedDate.value}T${localDateTime().slice(11)}`});const form=reactive(blankRecord());
const commonUnit=food=>food?.common_unit||food?.serving_unit;const commonUnitAmount=food=>food?.common_unit_amount??food?.serving_weight_g;const baseQuantity=(food,quantity,unit)=>unit===commonUnit(food)?Number(quantity)*Number(commonUnitAmount(food)):Number(quantity);
const isEditing=computed(()=>editingId.value!==null),libraryRecord=computed(()=>Boolean(form.food_id)),selectedFoodUnits=computed(()=>[...new Set([selectedFood.value?.unit||form.unit,commonUnit(selectedFood.value)].filter(Boolean))]),inlineFoodUnits=computed(()=>[...new Set([inlineFood.value?.unit||inlineDraft.unit,commonUnit(inlineFood.value)].filter(Boolean))]),computedCalories=computed(()=>{if(!form.quantity)return"";const alcoholQuantity=libraryRecord.value&&selectedFood.value?(selectedFood.value.unit==="ml"?baseQuantity(selectedFood.value,form.quantity,form.unit):0):(form.unit==="ml"?Number(form.quantity):0);return((Number(form.protein)||0)*4+(Number(form.carbs)||0)*4+(Number(form.fat)||0)*9+alcoholQuantity*Number(form.alcohol_abv||0)/100*.789*7).toFixed(1)});
const selectedDateLabel=computed(()=>new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric",weekday:"short"}).format(new Date(`${selectedDate.value}T00:00:00`)));const meals=computed(()=>[{label:"早餐",value:stats.breakfast},{label:"午餐",value:stats.lunch},{label:"晚餐",value:stats.dinner},{label:"加餐",value:stats.snack}]);const totalProgress=computed(()=>goals.calories?Math.min(stats.total/goals.calories*100,100):0);const goalsView=computed(()=>[{label:"卡路里",v:stats.total,g:goals.calories,u:"kcal"},{label:"碳水",v:stats.carbs,g:goals.carbs,u:"g"},{label:"蛋白质",v:stats.protein,g:goals.protein,u:"g"},{label:"脂肪",v:stats.fat,g:goals.fat,u:"g"}].map(x=>({...x,p:Math.min(x.v/x.g*100,100),r:Math.max(x.g-x.v,0),o:Math.max(x.v-x.g,0)})));const trendSummary=computed(()=>{const values=trend.value.map(item=>Number(item.calories)||0);if(!values.length)return{average:0,minimum:0,maximum:0};return{average:Math.round(values.reduce((sum,value)=>sum+value,0)/values.length),minimum:Math.round(Math.min(...values)),maximum:Math.round(Math.max(...values))}});
async function request(url,options){const r=await authFetch(url,options);if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(Array.isArray(b.detail)?b.detail[0]?.msg:b.detail||"请求失败")}return r.status===204?null:r.json()}
const settled=promise=>promise.then(data=>({data}),error=>({error}));
function syncUrl(replace=false){if(applyingHistory)return;const p=new URLSearchParams();p.set("view",currentView.value==="foods"?"food-library":currentView.value);p.set("date",selectedDate.value);p.set("trend",String(trendDays.value));history[replace?"replaceState":"pushState"]({},"",`${location.pathname}?${p}`)}
async function restoreUrlState(){applyingHistory=true;const state=readUrlState();currentView.value=state.view;selectedDate.value=state.date;trendDays.value=state.days;await nextTick();applyingHistory=false;if(currentView.value==="home")await loadDashboard()}
async function loadTrend(){
  const requestId=++trendRequestId,date=selectedDate.value,days=trendDays.value,key=cacheKeys.trend(date,days),d=encodeURIComponent(date);
  let networkResolved=false;
  const networkTask=settled(request(`/api/stats/trend?end_date=${d}&days=${days}`)).then(async result=>{
    if(result.error){if(requestId===trendRequestId)errorMessage.value=result.error.message;return}
    if(requestId!==trendRequestId||date!==selectedDate.value||days!==trendDays.value)return;
    networkResolved=true;trend.value=result.data;void writeCache(key,result.data);await nextTick();renderChart();
  });
  const cached=await readCache(key);
  if(cached&&!networkResolved&&requestId===trendRequestId&&date===selectedDate.value&&days===trendDays.value){trend.value=cached;await nextTick();renderChart()}
  await networkTask;
}
async function loadDashboard(){
  const requestId=++dashboardRequestId,date=selectedDate.value,recordsKey=cacheKeys.records(date),statsKey=cacheKeys.stats(date),d=encodeURIComponent(date);
  let networkResolved=false;
  loading.value=true;errorMessage.value="";void loadTrend();
  const networkTask=settled(Promise.all([request(`/api/records?date=${d}`),request(`/api/stats/daily?date=${d}`)])).then(result=>{
    if(result.error){if(requestId===dashboardRequestId)errorMessage.value=result.error.message;return}
    if(requestId!==dashboardRequestId||date!==selectedDate.value)return;
    networkResolved=true;const[recordData,statsData]=result.data;records.value=recordData;Object.assign(stats,statsData);void writeCache(recordsKey,recordData);void writeCache(statsKey,statsData);loading.value=false;
  });
  const[cachedRecords,cachedStats]=await Promise.all([readCache(recordsKey),readCache(statsKey)]);
  if(!networkResolved&&requestId===dashboardRequestId&&date===selectedDate.value){if(cachedRecords){records.value=cachedRecords;loading.value=false}if(cachedStats)Object.assign(stats,cachedStats)}
  await networkTask;if(requestId===dashboardRequestId)loading.value=false;
}
async function loadGoals(){
  let networkResolved=false;
  const networkTask=settled(request("/api/settings/goals")).then(result=>{if(result.error){errorMessage.value=result.error.message;return}networkResolved=true;Object.assign(goals,result.data);void writeCache(cacheKeys.goals,result.data)});
  const cached=await readCache(cacheKeys.goals);if(cached&&!networkResolved)Object.assign(goals,cached);await networkTask;
}
function handleGoalsSaved(value){Object.assign(goals,value);void writeCache(cacheKeys.goals,value)}
function chooseFood(food){selectedFood.value=food;Object.assign(form,{food_id:food.id,food_name:food.name,quantity:"",unit:food.unit,protein:"",fat:"",carbs:"",alcohol_abv:food.alcohol_abv||0,nutrition_source:"food_library",add_to_library:false})}function clearFood(){selectedFood.value=null;form.food_id=null;form.alcohol_abv=0;form.nutrition_source="manual";form.add_to_library=true}function recalcPreview(food=selectedFood.value){if(!food)return;if(!form.quantity){form.protein="";form.fat="";form.carbs="";return}const ratio=baseQuantity(food,form.quantity,form.unit)/food.base_amount;form.protein=+(food.protein*ratio).toFixed(2);form.fat=+(food.fat*ratio).toFixed(2);form.carbs=+(food.carbs*ratio).toFixed(2)}
function resetForm(){editingId.value=null;selectedFood.value=null;Object.assign(form,blankRecord())}async function editRecord(r){editingId.value=r.id;selectedFood.value=null;Object.assign(form,{food_name:r.food_name,quantity:r.quantity,unit:r.unit,food_id:r.food_id,protein:r.protein,fat:r.fat,carbs:r.carbs,alcohol_abv:r.alcohol_abv||0,nutrition_source:r.nutrition_source,add_to_library:false,meal_type:r.meal_type,eaten_at:localDateTime(r.eaten_at)});if(r.food_id){try{selectedFood.value=await request(`/api/foods/${r.food_id}`)}catch{selectedFood.value=null}}document.querySelector(".form-card")?.scrollIntoView({behavior:"smooth"})}
function updateMealFromTime(target,value){if(value)target.meal_type=getDefaultMealType(new Date(value))}async function startInlineEdit(r){inlineEditId.value=r.id;inlineFood.value=null;Object.assign(inlineDraft,{quantity:r.quantity,unit:r.unit,meal_type:r.meal_type,eaten_at:localDateTime(r.eaten_at)});if(r.food_id){try{inlineFood.value=await request(`/api/foods/${r.food_id}`)}catch{inlineFood.value=null}}}function cancelInlineEdit(event){event?.stopPropagation();inlineEditId.value=null;inlineFood.value=null;Object.assign(inlineDraft,{quantity:"",unit:"g",meal_type:"",eaten_at:""})}async function saveInlineQuantity(r){if(!Number(inlineDraft.quantity)||Number(inlineDraft.quantity)<=0){errorMessage.value="数量必须大于 0";return}inlineSaving.value=true;errorMessage.value="";try{const updated=await request(`/api/records/${r.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({food_name:r.food_name,quantity:Number(inlineDraft.quantity),unit:inlineDraft.unit,food_id:r.food_id,protein:r.protein,fat:r.fat,carbs:r.carbs,alcohol_abv:r.alcohol_abv||0,nutrition_source:r.nutrition_source,add_to_library:false,meal_type:inlineDraft.meal_type,eaten_at:inlineDraft.eaten_at})});cancelInlineEdit();notifyFoodUsageChanged();const target=updated.eaten_at.slice(0,10);if(target!==selectedDate.value)selectedDate.value=target;else await loadDashboard()}catch(e){errorMessage.value=e.message}finally{inlineSaving.value=false}}
async function saveRecord(){submitting.value=true;errorMessage.value="";try{const saved=await request(isEditing.value?`/api/records/${editingId.value}`:"/api/records",{method:isEditing.value?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,quantity:Number(form.quantity),protein:Number(form.protein||0),fat:Number(form.fat||0),carbs:Number(form.carbs||0)})});notifyFoodUsageChanged();const target=saved.eaten_at.slice(0,10);resetForm();if(target!==selectedDate.value)selectedDate.value=target;else await loadDashboard()}catch(e){errorMessage.value=e.message}finally{submitting.value=false}}
async function deleteRecord(id){try{await ensureUnlocked();recordToDelete.value=records.value.find(record=>record.id===id)||null}catch{}}async function confirmDeleteRecord(){if(!recordToDelete.value||deletingRecord.value)return;deletingRecord.value=true;errorMessage.value="";try{await request(`/api/records/${recordToDelete.value.id}`,{method:"DELETE"});recordToDelete.value=null;notifyFoodUsageChanged();await loadDashboard()}catch(error){errorMessage.value=error.message}finally{deletingRecord.value=false}}
async function handleAiSaved(){notifyFoodUsageChanged();await loadDashboard()}
function renderChart(){if(!chartElement.value)return;chart||=init(chartElement.value);chart.setOption({grid:{left:48,right:24,top:28,bottom:42},tooltip:{trigger:"axis",valueFormatter:value=>`${Math.round(value)} kcal`},xAxis:{type:"category",data:trend.value.map(i=>i.date.slice(5).replace("-","/"))},yAxis:{type:"value",minInterval:1,axisLabel:{formatter:value=>Math.round(value)}},series:[{type:"line",smooth:true,data:trend.value.map(i=>Math.round(i.calories)),lineStyle:{color:"#2f855a",width:3},areaStyle:{color:new graphic.LinearGradient(0,0,0,1,[{offset:0,color:"#4fac783d"},{offset:1,color:"#4fac7805"}])}}]});chart.resize()}
function recordNutrients(record){const values=[["C",record.carbs],["P",record.protein],["F",record.fat]];if(Number(record.alcohol_abv)>0)values.push(["A",Number(record.weight)*Number(record.alcohol_abv)/100*.789]);return values.map(([label,value])=>[label,Math.round(Number(value))]).filter(([,value])=>value>0).map(([label,value])=>`${label}${value}`).join(" · ")}
function requestUnlock(){unlockOpen.value=true;unlockError.value="";return new Promise((resolve,reject)=>{unlockResolve=resolve;unlockReject=reject})}async function submitUnlock(password){if(unlocking.value)return;unlocking.value=true;unlockError.value="";try{const response=await fetch("/api/auth/unlock",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.detail||"解锁失败");unlockOpen.value=false;unlockResolve?.();unlockResolve=unlockReject=null}catch(error){unlockError.value=error.message}finally{unlocking.value=false}}function cancelUnlock(){if(unlocking.value)return;unlockOpen.value=false;unlockReject?.(new Error("操作已取消"));unlockResolve=unlockReject=null}async function lockEditing(){errorMessage.value="";try{const response=await fetch("/api/auth/lock",{method:"POST"});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.detail||"锁定失败")}errorMessage.value="已锁定，下一次修改时需要重新输入密码"}catch(error){errorMessage.value=`锁定失败：${error.message}`}}setUnlockHandler(requestUnlock)
watch([()=>form.quantity,()=>form.unit],()=>recalcPreview());watch(selectedDate,()=>{if(!applyingHistory)syncUrl();resetForm();if(!applyingHistory)loadDashboard()});watch(trendDays,()=>{if(!applyingHistory){syncUrl();if(currentView.value==="home")loadTrend()}});watch(currentView,async(view,previous)=>{if(!applyingHistory)syncUrl();if(previous==="home"&&chart){chart.dispose();chart=null}if(view==="home"){await nextTick();renderChart()}});onMounted(async()=>{syncUrl(true);addEventListener("popstate",restoreUrlState);await Promise.all([loadGoals(),loadDashboard()])});onBeforeUnmount(()=>{setUnlockHandler(null);removeEventListener("popstate",restoreUrlState);chart?.dispose();chart=null});
</script>
<template><main class="page"><header class="hero"><div><p class="eyebrow">CALORIE TRACKER</p><h1>饮食记录</h1></div><div class="header-actions"><div v-if="currentView==='home'" class="date-controls"><button type="button" class="date-step" aria-label="上一天" title="上一天" @click="moveSelectedDate(-1)">‹</button><button type="button" class="today-button" @click="selectToday">今天</button><button type="button" class="date-step" aria-label="下一天" title="下一天" @click="moveSelectedDate(1)">›</button><label class="date-picker">查看日期<input v-model="selectedDate" type="date"/></label></div><nav><button :class="{active:currentView==='home'}" @click="currentView='home'">首页</button><button :class="{active:currentView==='foods'}" @click="currentView='foods'">食物库</button><button :class="{active:currentView==='settings'}" @click="currentView='settings'">设置</button><button class="lock-button" title="锁定写操作" @click="lockEditing">锁定</button></nav></div></header><SettingsView v-if="currentView==='settings'" @saved="handleGoalsSaved"/><FoodLibraryView v-else-if="currentView==='foods'"/><template v-else>
<section class="summary-grid"><article class="total-card" role="progressbar" :aria-valuenow="totalProgress.toFixed(0)" aria-valuemin="0" aria-valuemax="100" :style="{'--total-progress':totalProgress+'%'}"><span>{{selectedDateLabel}}总摄入</span><div><strong>{{Math.round(stats.total)}}</strong><small>kcal</small></div></article><article v-for="m in meals" :key="m.label" class="stat-card"><span>{{m.label}}</span><strong>{{Math.round(m.value)}} <small>kcal</small></strong></article></section><section class="goal-grid"><article v-for="g in goalsView" :key="g.label"><header><strong>{{g.label}}</strong><span>{{g.p.toFixed(0)}}%</span></header><div class="progress"><i :style="{width:g.p+'%'}"></i></div><p>已摄入 {{Math.round(g.v)}} / 目标 {{Math.round(g.g)}} {{g.u}}</p><small v-if="g.o>0">超过 {{Math.round(g.o)}} {{g.u}}</small><small v-else>剩余 {{Math.round(g.r)}} {{g.u}}</small></article></section>
<section class="card form-card" :class="{editing:isEditing}"><div class="section-heading"><div><p class="section-kicker">{{isEditing?'EDIT RECORD':'NEW RECORD'}}</p><h2>{{isEditing?'修改饮食记录':'添加饮食'}}</h2></div><button v-if="isEditing" class="text-button" @click="resetForm">取消编辑</button></div><form class="record-form" novalidate @submit.prevent="saveRecord"><label class="wide">从食物库搜索<FoodPicker :selected-id="form.food_id" @select="chooseFood" @clear="clearFood"/></label><label>食物名称<input v-model.trim="form.food_name" required :disabled="libraryRecord"/></label><label>数量<input v-model="form.quantity" required type="number" min="0" step="1"/></label><label>单位<select v-model="form.unit"><option v-for="unit in libraryRecord?selectedFoodUnits:['g','ml','个','份']" :key="unit">{{unit}}</option></select></label><label>卡路里（服务端自动）<input :value="computedCalories" disabled/></label><label v-if="form.alcohol_abv>0">酒精度 %<input :value="form.alcohol_abv" disabled/></label><label>碳水<input v-model="form.carbs" type="number" min="0" step="1" :disabled="libraryRecord"/></label><label>蛋白质<input v-model="form.protein" type="number" min="0" step="1" :disabled="libraryRecord"/></label><label>脂肪<input v-model="form.fat" type="number" min="0" step="1" :disabled="libraryRecord"/></label><label>餐次<select v-model="form.meal_type"><option>早餐</option><option>午餐</option><option>晚餐</option><option>加餐</option></select></label><label>食用时间<input v-model="form.eaten_at" required type="datetime-local" @change="updateMealFromTime(form,form.eaten_at)"/></label><label v-if="!libraryRecord" class="checkbox"><input v-model="form.add_to_library" type="checkbox"/>同名食物不存在时加入食物库</label><button class="primary" :disabled="submitting">{{submitting?'保存中…':isEditing?'保存修改':'添加记录'}}</button></form><p v-if="errorMessage" class="error">{{errorMessage}}</p></section>
<AiEntry @saved="handleAiSaved"/>
<div class="content-grid"><section class="card"><div class="section-heading"><div><p class="section-kicker">DAILY LOG</p><h2>{{selectedDateLabel}}饮食</h2></div><span>{{records.length}} 条记录</span></div><p v-if="loading" class="empty">正在加载…</p><p v-else-if="!records.length" class="empty">这一天还没有饮食记录。</p><ul v-else class="record-list"><li v-for="r in records" :key="r.id" class="record-item" tabindex="0" @click="inlineEditId!==r.id&&startInlineEdit(r)" @keydown.enter.self="inlineEditId!==r.id&&startInlineEdit(r)"><div class="meal-badge">{{r.meal_type}}</div><div class="record-main"><strong>{{r.food_name}} <i v-if="r.nutrition_source==='ai_estimated'" class="source-tag ai_estimated">估算</i></strong><span v-if="inlineEditId!==r.id">{{r.quantity}} {{r.unit}} · {{localDateTime(r.eaten_at).slice(11)}}</span><div v-else class="inline-edit-fields"><label>数量<input v-model="inlineDraft.quantity" type="number" min="0" step="1" autofocus/></label><label>单位<select v-model="inlineDraft.unit" :disabled="!inlineFood?.serving_unit"><option v-for="unit in inlineFoodUnits" :key="unit">{{unit}}</option></select></label><label>餐次<select v-model="inlineDraft.meal_type"><option>早餐</option><option>午餐</option><option>晚餐</option><option>加餐</option></select></label><label>时间<input v-model="inlineDraft.eaten_at" type="datetime-local" @change="updateMealFromTime(inlineDraft,inlineDraft.eaten_at)"/></label></div><small v-if="recordNutrients(r)">{{recordNutrients(r)}}</small></div><div class="calories"><strong>{{Math.round(r.calories)}}</strong><span>kcal</span></div><div class="actions" v-if="inlineEditId!==r.id"><button class="delete" @click.stop="deleteRecord(r.id)">删除</button></div><div class="actions inline-actions" v-else><button class="edit" :disabled="inlineSaving" @click="saveInlineQuantity(r)">{{inlineSaving?'保存中…':'保存'}}</button><button class="text-button" @click="cancelInlineEdit">取消</button></div></li></ul></section><section class="card trend-card"><div class="section-heading"><div><p class="section-kicker">{{trendDays}} DAY TREND</p><h2>卡路里趋势</h2></div><div class="trend-heading-actions"><div class="trend-summary"><span>平均 <strong>{{trendSummary.average}}</strong></span><span>最低 <strong>{{trendSummary.minimum}}</strong></span><span>最高 <strong>{{trendSummary.maximum}}</strong></span></div><div class="trend-range"><button :class="{active:trendDays===7}" @click="trendDays=7">7天</button><button :class="{active:trendDays===30}" @click="trendDays=30">30天</button></div></div></div><div ref="chartElement" class="chart"></div></section></div>
</template><ConfirmDialog :open="Boolean(recordToDelete)" :item-name="recordToDelete?.food_name||''" :loading="deletingRecord" @cancel="recordToDelete=null" @confirm="confirmDeleteRecord"/><UnlockDialog :open="unlockOpen" :loading="unlocking" :error="unlockError" @cancel="cancelUnlock" @unlock="submitUnlock"/></main></template>
